export const IMG_URL =
  "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/";

export const SWIGGY_API =
  "https://cors-anywhere.herokuapp.com/https://www.swiggy.com/dapi/restaurants/list/v5?lat=25.3176452&lng=82.9739144&offset=15&sortBy=RELEVANCE&pageType=SEE_ALL&page_type=DESKTOP_SEE_ALL_LISTING";

export const SWIGGY_MENU_API =
  "https://cors-anywhere.herokuapp.com/https://www.swiggy.com/dapi/menu/pl?page-type=REGULAR_MENU&complete-menu=true&lat=21.1702401&lng=72.83106070000001&&submitAction=ENTER&restaurantId=";

export const CART_IMAGE_URL =
  "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto/2xempty_cart_yfxml0";

export const restaurantData = [
  {
    cardType: "restaurant",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "restaurant",
      data: {
        type: "F",
        id: "666091",
        name: "Vadilal Ice Cream",
        uuid: "b49f94d4-f072-4ff3-a2ee-3906fd2d0c5b",
        city: "77",
        area: "Sigra",
        totalRatingsString: "",
        cloudinaryImageId: "554235ad5fc25e3ace1afddae17822ae",
        cuisines: ["Ice Cream", "Desserts"],
        tags: [],
        costForTwo: 25000,
        costForTwoString: "₹250 FOR TWO",
        deliveryTime: 36,
        minDeliveryTime: 36,
        maxDeliveryTime: 36,
        slaString: "36 MINS",
        lastMileTravel: 0,
        slugs: {
          restaurant: "vadilal-ice-cream-sigra-sigra-3",
          city: "Varanasi",
        },
        cityState: "77",
        address: "",
        locality: "Shivdaspur",
        parentId: 11745,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "BASE_DISTANCE",
              fee: 1500,
              message: "",
            },
            {
              name: "BASE_TIME",
              fee: 0,
              message: "",
            },
            {
              name: "ANCILLARY_SURGE_FEE",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 1500,
          message: "",
          title: "Delivery Charge",
          amount: "1500",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "2.3 kms",
        hasSurge: false,
        cta: {
          link: "swiggy://menu?restaurant_id=666091",
          type: "DEEPLINK",
          text: "RESTAURANT_MENU",
        },
        sla: {
          restaurantId: "",
          deliveryTime: 36,
          minDeliveryTime: 36,
          maxDeliveryTime: 36,
          lastMileTravel: 0,
          lastMileDistance: 2.3,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "4.7",
        totalRatings: 0,
        new: false,
      },
      subtype: "basic",
    },
    parentWidget: false,
  },
  {
    cardType: "restaurant",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "restaurant",
      data: {
        type: "F",
        id: "304366",
        name: "Kwality Walls Frozen Dessert and Ice Cream Shop",
        uuid: "90de60fd-518a-4bc7-b837-e3cdd3d7aa24",
        city: "77",
        area: "Nadesar",
        totalRatingsString: "",
        cloudinaryImageId: "k5oaokuxwedtcdk2n79y",
        cuisines: ["Desserts", "Ice Cream", "Ice Cream Cakes"],
        tags: [],
        costForTwo: 30000,
        costForTwoString: "₹300 FOR TWO",
        deliveryTime: 35,
        minDeliveryTime: 35,
        maxDeliveryTime: 35,
        slaString: "35 MINS",
        lastMileTravel: 0,
        slugs: {
          restaurant: "kwality-walls-ashapur-ashapur-2",
          city: "Varanasi",
        },
        cityState: "77",
        address: "",
        locality: "Ashapur",
        parentId: 582,
        unserviceable: false,
        veg: true,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "BASE_DISTANCE",
              fee: 4600,
              message: "",
            },
            {
              name: "BASE_TIME",
              fee: 0,
              message: "",
            },
            {
              name: "ANCILLARY_SURGE_FEE",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 4600,
          message: "",
          title: "Delivery Charge",
          amount: "4600",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID:
          "cid=7043569~p=2~eid=00000188-c2b1-83d9-093b-2f12005a0210~56421",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "7 kms",
        hasSurge: false,
        cta: {
          link: "swiggy://menu?restaurant_id=304366",
          type: "DEEPLINK",
          text: "RESTAURANT_MENU",
        },
        sla: {
          restaurantId: "",
          deliveryTime: 35,
          minDeliveryTime: 35,
          maxDeliveryTime: 35,
          lastMileTravel: 0,
          lastMileDistance: 7,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: true,
        avgRating: "4.4",
        totalRatings: 0,
        new: false,
      },
      subtype: "basic",
    },
    parentWidget: false,
  },
  {
    cardType: "restaurant",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "restaurant",
      data: {
        type: "F",
        id: "538975",
        name: "7th Heaven",
        uuid: "aca3cc52-45fd-47fd-b17d-1fa6d0a72185",
        city: "77",
        area: "Bhelupur",
        totalRatingsString: "",
        cloudinaryImageId: "f4fyvaxlkonjz1har66b",
        cuisines: ["Bakery", "Desserts", "Pizzas"],
        tags: [],
        costForTwo: 30000,
        costForTwoString: "₹300 FOR TWO",
        deliveryTime: 29,
        minDeliveryTime: 29,
        maxDeliveryTime: 29,
        slaString: "29 MINS",
        lastMileTravel: 0,
        slugs: {
          restaurant: "7th-heaven-lanka-lanka",
          city: "Varanasi",
        },
        cityState: "77",
        address: "",
        locality: "Jawahar Nagar Colony",
        parentId: 19,
        unserviceable: false,
        veg: true,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "BASE_DISTANCE",
              fee: 2100,
              message: "",
            },
            {
              name: "BASE_TIME",
              fee: 0,
              message: "",
            },
            {
              name: "ANCILLARY_SURGE_FEE",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 2100,
          message: "",
          title: "Delivery Charge",
          amount: "2100",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "4.9 kms",
        hasSurge: false,
        cta: {
          link: "swiggy://menu?restaurant_id=538975",
          type: "DEEPLINK",
          text: "RESTAURANT_MENU",
        },
        sla: {
          restaurantId: "",
          deliveryTime: 29,
          minDeliveryTime: 29,
          maxDeliveryTime: 29,
          lastMileTravel: 0,
          lastMileDistance: 4.9,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "4.2",
        totalRatings: 0,
        new: false,
      },
      subtype: "basic",
    },
    parentWidget: false,
  },
  {
    cardType: "restaurant",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "restaurant",
      data: {
        type: "F",
        id: "234903",
        name: "Burger King",
        uuid: "9db6ceb1-2c97-4f00-a22e-1572e63a3e56",
        city: "77",
        area: "Sigra",
        totalRatingsString: "",
        cloudinaryImageId: "e33e1d3ba7d6b2bb0d45e1001b731fcf",
        cuisines: ["Burgers", "American"],
        tags: [],
        costForTwo: 35000,
        costForTwoString: "₹350 FOR TWO",
        deliveryTime: 33,
        minDeliveryTime: 33,
        maxDeliveryTime: 33,
        slaString: "33 MINS",
        lastMileTravel: 0,
        slugs: {
          restaurant: "burger-king-shastri-nagar-sigra",
          city: "Varanasi",
        },
        cityState: "77",
        address: "",
        locality: "Sigra",
        parentId: 166,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfoV2: {
          header: "",
          shortDescriptionList: [],
          descriptionList: [],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "BASE_DISTANCE",
              fee: 1500,
              message: "",
            },
            {
              name: "BASE_TIME",
              fee: 0,
              message: "",
            },
            {
              name: "ANCILLARY_SURGE_FEE",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 1500,
          message: "",
          title: "Delivery Charge",
          amount: "1500",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "2.6 kms",
        hasSurge: false,
        cta: {
          link: "swiggy://menu?restaurant_id=234903",
          type: "DEEPLINK",
          text: "RESTAURANT_MENU",
        },
        sla: {
          restaurantId: "",
          deliveryTime: 33,
          minDeliveryTime: 33,
          maxDeliveryTime: 33,
          lastMileTravel: 0,
          lastMileDistance: 2.6,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "4.1",
        totalRatings: 0,
        new: false,
      },
      subtype: "basic",
    },
    parentWidget: false,
  },
  {
    cardType: "restaurant",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "restaurant",
      data: {
        type: "F",
        id: "277682",
        name: "99 Chickens",
        uuid: "78055e6c-2286-4ce2-90a4-581cd08702c7",
        city: "77",
        area: "Bhelupur",
        totalRatingsString: "",
        cloudinaryImageId: "ixshl9loiaz1ebfgsgut",
        cuisines: ["Pizzas", "Desserts", "Beverages", "Snacks", "American"],
        tags: [],
        costForTwo: 25000,
        costForTwoString: "₹250 FOR TWO",
        deliveryTime: 39,
        minDeliveryTime: 39,
        maxDeliveryTime: 39,
        slaString: "39 MINS",
        lastMileTravel: 0,
        slugs: {
          restaurant: "99-chickens-lanka-lanka-2",
          city: "Varanasi",
        },
        cityState: "77",
        address: "",
        locality: "Gurudham Chauraha",
        parentId: 24382,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfoV2: {
          header: "",
          shortDescriptionList: [],
          descriptionList: [],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "BASE_DISTANCE",
              fee: 3400,
              message: "",
            },
            {
              name: "BASE_TIME",
              fee: 0,
              message: "",
            },
            {
              name: "ANCILLARY_SURGE_FEE",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 3400,
          message: "",
          title: "Delivery Charge",
          amount: "3400",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID:
          "cid=6973116~p=3~eid=00000188-c2b1-83d9-093b-2f13005a0303~56421",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "5.6 kms",
        hasSurge: false,
        cta: {
          link: "swiggy://menu?restaurant_id=277682",
          type: "DEEPLINK",
          text: "RESTAURANT_MENU",
        },
        sla: {
          restaurantId: "",
          deliveryTime: 39,
          minDeliveryTime: 39,
          maxDeliveryTime: 39,
          lastMileTravel: 0,
          lastMileDistance: 5.6,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: true,
        avgRating: "4.1",
        totalRatings: 0,
        new: false,
      },
      subtype: "basic",
    },
    parentWidget: false,
  },
  {
    cardType: "restaurant",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "restaurant",
      data: {
        type: "F",
        id: "253783",
        name: "McDonald's",
        uuid: "ec843d46-f43a-403a-bad5-641a65952e10",
        city: "77",
        area: "Nadesar",
        totalRatingsString: "",
        cloudinaryImageId: "08eee882fda81b68e5c36e3a5d89d8c0",
        cuisines: ["American"],
        tags: [],
        costForTwo: 40000,
        costForTwoString: "₹400 FOR TWO",
        deliveryTime: 25,
        minDeliveryTime: 25,
        maxDeliveryTime: 25,
        slaString: "25 MINS",
        lastMileTravel: 0,
        slugs: {
          restaurant: "mcdonalds-up-varanasi-jhv-mall-sigra",
          city: "Varanasi",
        },
        cityState: "77",
        address: "",
        locality: "JHV Mall",
        parentId: 630,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfoV2: {
          header: "",
          shortDescriptionList: [],
          descriptionList: [],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "BASE_DISTANCE",
              fee: 1500,
              message: "",
            },
            {
              name: "BASE_TIME",
              fee: 0,
              message: "",
            },
            {
              name: "ANCILLARY_SURGE_FEE",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 1500,
          message: "",
          title: "Delivery Charge",
          amount: "1500",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "2.8 kms",
        hasSurge: false,
        cta: {
          link: "swiggy://menu?restaurant_id=253783",
          type: "DEEPLINK",
          text: "RESTAURANT_MENU",
        },
        sla: {
          restaurantId: "",
          deliveryTime: 25,
          minDeliveryTime: 25,
          maxDeliveryTime: 25,
          lastMileTravel: 0,
          lastMileDistance: 2.8,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "4.0",
        totalRatings: 0,
        new: false,
      },
      subtype: "basic",
    },
    parentWidget: false,
  },
];
